import { tradingDataType } from "@/utils/types";

export const tradingData : tradingDataType[] = [
    {
      id: 1,
      openTime: "09:05:30",
      tradeSide: "PUT",
      instrument: "Nifty",
      volume: 150,
      netPL: "10.25k",
    },
    {
        id: 2,
        openTime: "09:05:30",
        tradeSide: "CALL",
        instrument: "Nifty Bank",
        volume: 25,
        netPL: "10.25k",
    },
    {
        id: 3,
        openTime: "09:05:30",
        tradeSide: "PUT",
        instrument: "Nifty",
        volume: 150,
        netPL: "10.25k",
      },
      {
          id: 4,
          openTime: "09:05:30",
          tradeSide: "CALL",
          instrument: "Nifty Bank",
          volume: 25,
          netPL: "10.25k",
      },
      {
        id: 5,
        openTime: "09:05:30",
        tradeSide: "PUT",
        instrument: "Nifty",
        volume: 150,
        netPL: "10.25k",
      },
      {
          id: 6,
          openTime: "09:05:30",
          tradeSide: "CALL",
          instrument: "Nifty Bank",
          volume: 25,
          netPL: "10.25k",
      },
      {
        id: 7,
        openTime: "09:05:30",
        tradeSide: "PUT",
        instrument: "Nifty",
        volume: 150,
        netPL: "10.25k",
      },
      {
          id: 8,
          openTime: "09:05:30",
          tradeSide: "CALL",
          instrument: "Nifty Bank",
          volume: 25,
          netPL: "10.25k",
      },
      {
        id: 9,
        openTime: "09:05:30",
        tradeSide: "PUT",
        instrument: "Nifty",
        volume: 150,
        netPL: "10.25k",
      },
      {
          id: 10,
          openTime: "09:05:30",
          tradeSide: "CALL",
          instrument: "Nifty Bank",
          volume: 25,
          netPL: "10.25k",
      },
      {
        id: 11,
        openTime: "09:05:30",
        tradeSide: "PUT",
        instrument: "Nifty",
        volume: 150,
        netPL: "10.25k",
      },
      {
          id: 12,
          openTime: "09:05:30",
          tradeSide: "CALL",
          instrument: "Nifty Bank",
          volume: 25,
          netPL: "10.25k",
      },
      {
        id: 13,
        openTime: "09:05:30",
        tradeSide: "PUT",
        instrument: "Nifty",
        volume: 150,
        netPL: "10.25k",
      },
      {
          id: 14,
          openTime: "09:05:30",
          tradeSide: "CALL",
          instrument: "Nifty Bank",
          volume: 25,
          netPL: "10.25k",
      },
      {
        id: 15,
        openTime: "09:05:30",
        tradeSide: "PUT",
        instrument: "Nifty",
        volume: 150,
        netPL: "10.25k",
      },
      {
          id: 16,
          openTime: "09:05:30",
          tradeSide: "CALL",
          instrument: "Nifty Bank",
          volume: 25,
          netPL: "10.25k",
      },
  ];      